### ISSUE TITLE
Doesnt Work With HTTPS

### ISSUE THREAD

**Issue by bonedaddy** [zadam/trilium-web-clipper#15]
If your server is listening on HTTPS, it doesn't look like you can connect to it as the web clipper attempts to connect to `http://...`

**Comment by zadam** [comment]
Do you have configured https in the settings?

I myself use it with https no problem:

![](https://user-images.githubusercontent.com/617641/87146985-1c1c4680-c2ac-11ea-8471-a9f6c1ec71ec.png)

**Comment by bonedaddy** [comment]
Actually you are correct, my mistake.
