### ISSUE TITLE
FR: Can web clipper save the current URL alongside when text note is created

### ISSUE THREAD

**Issue by hakanu** [zadam/trilium-web-clipper#2]
This would be a powerful bookmarking feature.

And awesome job with the clipper. I'm living in trilium these days and this can easily make me ditch Pocket for reading list!

**Comment by tbnorth** [comment]
Yes, save the full URL (including #fragment) both as @pageUrl, and as a clickable link at the top of the created page, for all three clip types - that would be great :)

**Comment by zadam** [comment]
Added a while ago:

![image](https://user-images.githubusercontent.com/617641/139492756-2e40dea6-1a23-4900-8977-2d3215e9210e.png)
