### ISSUE TITLE
[Feature Request] Option to configure Trilium destination node

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium-web-clipper#20]
I just recently discovered the Firefox extension and I am very impressed! Great work!

Currently snips are saved to a Calendar node:
![image](https://user-images.githubusercontent.com/10717998/93380599-6c280400-f82d-11ea-86fb-bf0ea8d7d41a.png)

It would be nice to be able to configure a different destination for clips. My idea was to be able to specify a node like 'Inbox' where i could save clips and then file them away to different nodes at a later time.

**Comment by zadam** [comment]
Yes, as is described in https://github.com/zadam/trilium/wiki/Web-clipper 

> Trilium will save these clippings as a new child note under a "clipper inbox" note. Clipper inbox is:
> 
> *   if there's a note with [label](https://github.com/zadam/trilium/wiki/Attributes) `#clipperInbox`, then this note is used as parent for the clipped notes
> *   otherwise [day note](https://github.com/zadam/trilium/wiki/Day-notes) is used as a parent

**Comment by meichthys** [comment]
I just saw that part of the docs. Thanks!
