### ISSUE TITLE
Add option to save current page's url

### ISSUE THREAD

**Issue by 0syf3r** [zadam/trilium-web-clipper#26]
There's already a way to save a link's url, so I think this feature should be pretty easy to add.

**Comment by 0syf3r** [comment]
Oh, and having the ability to attach an optional note to the url would pretty sweet.
 #2 is also related.

**Comment by gked** [comment]
I feel like this has been implemented already so it warrants the closure of this issue?

**Comment by zadam** [comment]
Yes, that's true, closing.

![image](https://user-images.githubusercontent.com/617641/139492685-4ed449fc-775d-4d1c-825c-c61bdf78d5da.png)
