### ISSUE TITLE
Potential Harm Of Clipping Pages With JavaScript, Trackers, etc..

### ISSUE THREAD

**Issue by bonedaddy** [zadam/trilium-web-clipper#27]
Does web clipper copy a web page verbatim? ie If clipping a web page that includes harmful javascript code, or ads, cookies, etc... and you view the clipped content through the trilium frontend, would you be at risk of any potential information leakage, or potentially executing harmful javascript code?

**Comment by zadam** [comment]
Hi, clipper does not copy the web pages verbatim, it uses [https://github.com/mozilla/readability](https://github.com/mozilla/readability) script to simplify the page before inserting it into trilium, as part of that all javascript (and CSS AFAIK) are stripped away.

**Comment by bonedaddy** [comment]
Makes sense, thanks!
