### ISSUE TITLE
Possibility to save  web-pages, selected text, screenshot in another folder ? 

### ISSUE THREAD

**Issue by Enrico68** [zadam/trilium-web-clipper#40]
I would like to use web-clipper savings in another folder (actually it saves in Journal folder).  Is there a possibility to save it in another folder ( for example Inbox ) .

**Comment by zadam** [comment]
Hi, yes, mark the Inbox note with `clipperInbox` label and then notes will come there - this is documented here: https://github.com/zadam/trilium/wiki/Web-clipper

**Comment by Enrico68** [comment]
ok . Thanks !
