### ISSUE TITLE
[issue] How can I find the required "username“ when using "Trilium server instance"

### ISSUE THREAD

**Issue by guzongmin** [zadam/trilium-web-clipper#41]
I am using Trilium with docker instance. It means that I download Trilium from [dockerhub](https://hub.docker.com/r/zadam/trilium) and launch it with docker. It works.  When I was using the "setup" page to set the password, it did not ask me to select a username. And I do not find the username in the "options" menu. So I think Trilium does not require a password.
I also want to use trilium-web-clipper with the Trilium instance. But I can not even log in to the system. trilium-web-clipper requires a username and password. But I only have the password.
How can I work it out? Is there any default username for Trilium, or Trilium does not need the username anymore?

**Comment by zadam** [comment]
Hi, up until version 0.49 Trilium required a username. But it wasn't really used for anything so it has been dropped with 0.50.

In the web clipper simply leave this blank, it will be ignored on the server side.

**Comment by guzongmin** [comment]
Thanks for your reply.

**Comment by Lewiscowles1986** [comment]
This doesn't work in chrome, and so I used the name `trilium`. It seems to work! This should really be added to the Trilium wiki
