### ISSUE TITLE
"openNoteInTrilium" not working for "open-in-browser"

### ISSUE THREAD

**Issue by Matapii** [zadam/trilium-web-clipper#47]
Recently, I set up the web clipper to work with the Trilium server instance. It seems the Link "Open Note in Trilium" from the "Save Selection to Trilium" is not working. The link in fact opens the Trilium web interface, but it does not navigate to the newly created note. 

According to https://github.com/zadam/trilium-web-clipper/blob/711e4f8ebd718c6616a6e21f708b84c30b4fda2e/background.js#L403 a URL is generated according to the pattern `triliumServerUrl + '/#' + request.noteId`. However, the latter part with the noteId is apparently ignored by the web application.

**Comment by zadam** [comment]
Hello, this is probably the same bug as reported and fixed in https://github.com/zadam/trilium/issues/3571

Version with a fix will be released soon.

**Comment by zadam** [comment]
Should be fixed in 0.58.8.
