### ISSUE TITLE
#clipperInbox not used for all clips

### ISSUE THREAD

**Issue by sottey** [zadam/trilium-web-clipper#56]
First, thank you for the amazing software. I replaced Notion and have never regretted if.

I am finding that Items saved from the webClipper are not always put in the location specified by the #clipperInbox attribute. 

### Findings:
1) Add the #clipperInbox attribute to a note and ensure no other note has that attribute
2) Install Trilium WebClipper 
3) Select Cropped Screenshot option from Web Clipper. **Expected**: New note in the Inbox **Result**: Note present - Pass
3) Select Whole Screenshot option from Web Clipper. **Expected**: New note in the Inbox **Result**: Note present - Pass
4) Select Save Whole Page option from Web Clipper. **Expected**: New note in the Inbox **Result**: Note in Daily Journal - Fail
5) Select Link with note option from Web Clipper. **Expected**: New note in the Inbox **Result**: Note in Daily Journal - Fail
6) Select Save List of tabs option from Web Clipper. **Expected**: New note in the Inbox **Result**: Note in Daily Journal - Fail

### Environment:
**Browser**: Chrome 116.0.5845.96
**OS**: macOS Sonoma 14
**Trilium**: Version. 0.61.5-beta (DB Ver: 225, Sync Ver: 31, Build Date: 2023-08-16T23:02:15+02:00, Build revision: 3f7a5504c77263a7118cede5c0d9b450ba37f424)
**WebClipper**: version 1.0.1
**Server**: Running from a Docker Container in a Digital Ocean Droplet

**Comment by zadam** [comment]
Hi, sorry I guess I missed this issue. Fixed in zadam/trilium@2b4cbb5
